//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITD.ETC.VETC.Synchronization.MtcAndEtc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITD.ETC.VETC.Synchronization.MtcAndEtc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommuterTicketTransactionData.
        /// </summary>
        internal static string CommuterTicketTransactionDataJobName {
            get {
                return ResourceManager.GetString("CommuterTicketTransactionDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoatVeThang_Qui.
        /// </summary>
        internal static string CommuterTicketTransactionTableName {
            get {
                return ResourceManager.GetString("CommuterTicketTransactionTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComuterTicket.
        /// </summary>
        internal static string ComuterTicketDataJobName {
            get {
                return ResourceManager.GetString("ComuterTicketDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeData.
        /// </summary>
        internal static string EmployeeDataJobName {
            get {
                return ResourceManager.GetString("EmployeeDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EtagRegisterData.
        /// </summary>
        internal static string EtagRegisterDataJobName {
            get {
                return ResourceManager.GetString("EtagRegisterDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EtagThang.
        /// </summary>
        internal static string EtagRegisterTableName {
            get {
                return ResourceManager.GetString("EtagRegisterTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EtagTransactionData.
        /// </summary>
        internal static string EtagTransactionDataJobName {
            get {
                return ResourceManager.GetString("EtagTransactionDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRP_tblCheckObuAccount_RFID.
        /// </summary>
        internal static string EtagTransactionTableName {
            get {
                return ResourceManager.GetString("EtagTransactionTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageDataUpload.
        /// </summary>
        internal static string ImageDataJobName {
            get {
                return ResourceManager.GetString("ImageDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không kết nối được cơ sở dữ liệu!.
        /// </summary>
        internal static string NoDatabaseConnection {
            get {
                return ResourceManager.GetString("NoDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialBTCTransactionData.
        /// </summary>
        internal static string SpecialBTCTransactionDataJobName {
            get {
                return ResourceManager.GetString("SpecialBTCTransactionDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoatVe_BTC.
        /// </summary>
        internal static string SpecialBTCTransactionTableName {
            get {
                return ResourceManager.GetString("SpecialBTCTransactionTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialTransactionData.
        /// </summary>
        internal static string SpecialTransactionDataJobName {
            get {
                return ResourceManager.GetString("SpecialTransactionDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceOpen.
        /// </summary>
        internal static string SpecialTransactionTableName {
            get {
                return ResourceManager.GetString("SpecialTransactionTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TollTicketData.
        /// </summary>
        internal static string TollTicketDataJobName {
            get {
                return ResourceManager.GetString("TollTicketDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TollTicketTransactionData.
        /// </summary>
        internal static string TollTicketTransactionDataJobName {
            get {
                return ResourceManager.GetString("TollTicketTransactionDataJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoatVeVangLai.
        /// </summary>
        internal static string TollTicketTransactionTableName {
            get {
                return ResourceManager.GetString("TollTicketTransactionTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehiclePlateData.
        /// </summary>
        internal static string VehiclePlateJobName {
            get {
                return ResourceManager.GetString("VehiclePlateJobName", resourceCulture);
            }
        }
    }
}
